[package]
name = "servesink"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
numaflow = { git = "https://github.com/BulkBeing/numaflow-rs.git", rev = "6eb7f3865d42a8ab11ade51622dc4d8feda25b5e" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dependencies.reqwest]
version = "0.12.7"
default-features = false
features = ["rustls-tls"]